# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    - cron: "30 * * * *"
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install  pycryptodome requests loguru opencv-python-headless numpy pillow
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: 检查当前目录
      run: ls -lah
      
    - name: Python with access_token.py
      run: |
        python3 access_token.py
        
    - name: Post-run verification
      run: |
        echo "最终目录权限:"
        ls -ld /home/runner/work/bid
        
        echo "文件权限详情:"
        ls -l /home/runner/work/bid/access_token.json
        
        echo "文件内容验证:"
        cat /home/runner/work/bid/access_token.json
